package ProjectPlus.editor;

/*Generated by MPS */


public class HTMLAdmin {

  public String head() {
    String top = "<!DOCTYPE html>" + "\n" + "<html>" + "\n" + "<head>" + "\n" + "<meta charset='utf-8'>" + "\n" + "<title>PROYECTO ++</title>" + "\n" + "<link href='https://fonts.googleapis.com/css?family=Dosis&display=swap' rel='stylesheet'>" + "</head>" + "\n";
    return top;
  }

  public String style() {
    String top = "<style type='text/css'>" + "\n" + "*{" + "\n" + "font-family: 'Dosis', sans-serif;" + "\n" + "}" + "\n" + "body{" + "\n" + "text-align: center;" + "\n" + "}" + "\n" + ".hero{" + "\n" + "width: 90%;" + "\n" + "margin: auto;" + "\n" + "}" + "\n" + ".navbar{" + "\n" + "margin: 30px auto;" + "\n" + "display: flex;" + "\n" + "align-items: center;" + "\n" + "}" + "\n" + "ul{" + "\n" + "flex: 1;" + "\n" + "text-align: right;" + "\n" + "}" + "ul li{" + "\n" + "display: inline-block;" + "\n" + "list-style: none;" + "\n" + "margin: 0 2px;" + "\n" + "}" + "\n" + "ul li a{" + "\n" + "text-decoration: none;" + "\n" + "color: #000;" + "\n" + "padding: 0 10px;" + "\n" + "position: relative;" + "\n" + "}" + "\n" + "ul li a::after{" + "\n" + "content: '';" + "\n" + "width: 0;" + "\n" + "height: 10px;" + "\n" + "background: #f14a60;" + "\n" + "position: absolute;" + "\n" + "left: 50%;" + "\n" + "transform: translateX(-50%);" + "\n" + "top: -15px;" + "\n" + "transition: 0.5s;" + "\n" + "}" + "\n" + "ul li a:hover::after{" + "\n" + "width: 100%;" + "\n" + "}" + "\n" + "span{" + "\n" + "color: #f14a60;" + "\n" + "}" + "\n" + "table{" + "\n" + "position: relative;" + "\n" + "margin: 0 auto;" + "\n" + "width: 60%;" + "\n" + "background: #fafafa;" + "\n" + "text-align: center;" + "\n" + "border-collapse: collapse;" + "\n" + "border-spacing: 0;" + "\n" + "border-radius: 12px 12px 0 0;" + "\n" + "overflow: hidden;" + "\n" + "box-shadow: 0 2px 12px rgba(32, 32, 32, .3);" + "\n" + "}" + "\n" + "th{" + "\n" + "background: #f14a60;" + "\n" + "color: #fafafa;" + "\n" + "text-transform: uppercase;" + "\n" + "}" + "\n" + "th, td{" + "\n" + "padding: 5px 15px;" + "\n" + "}" + "\n" + "tr:nth-child(odd){" + "\n" + "background: #eeeeee;" + "\n" + "}" + "\n" + "</style>" + "\n";
    return top;
  }

  public String navbar() {
    String top = "<body>" + "\n" + "<div class='hero'>" + "\n" + "<div class='navbar'>" + "\n" + "<h1>Project++ Planning</h1>" + "\n" + "<ul>" + "\n" + "<li><a href='#'>Project Data</a></li>" + "\n" + "<li><a href='#'>Business Understanding</a></li>" + "\n" + "<li><a href='#'>Data Understanding</a></li>" + "\n" + "<li><a href='#'>Data Preparation</a></li>" + "\n" + "<li><a href='#'>Modeling</a></li>" + "\n" + "<li><a href='#'>Evaluation</a></li>" + "\n" + "<li><a href='#'>Deployment</a></li>" + "\n" + "</ul>" + "\n" + "</div>" + "\n" + "</div>" + "\n";
    return top;
  }

  public String end() {
    String top = "</body>" + "\n" + "</html>";
    return top;
  }


}
